# Generated by Django 4.2.7 on 2023-11-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleimage',
            name='exclude_from_study',
            field=models.BooleanField(default=False),
        ),
    ]
