# Generated by Django 4.1.7 on 2023-11-09 22:06

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='sample_a',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='sample_b',
        ),
        migrations.AlterField(
            model_name='sampleimage',
            name='img',
            field=models.ImageField(upload_to=main.models.content_file_name),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_control', models.BooleanField(default=False)),
                ('sample_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_a', to='main.sampleimage')),
                ('sample_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_b', to='main.sampleimage')),
            ],
        ),
    ]
