# Generated by Django 4.2.7 on 2023-11-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sampleimage_exclude_from_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
    ]
