# Generated by Django 4.2.7 on 2023-11-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_player_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
