# Generated by Django 4.1.7 on 2023-11-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
