# Generated by Django 4.1.7 on 2023-11-10 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_competitor_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='sample_a_wins',
        ),
        migrations.RemoveField(
            model_name='player',
            name='accuracy',
        ),
        migrations.AddField(
            model_name='answer',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='main.sampleimage'),
        ),
    ]
