# Generated by Django 4.1.7 on 2023-11-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_answer_sample_a_wins_remove_player_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
    ]
