# Generated by Django 4.2.7 on 2023-11-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_player_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='correct_control_answers',
            field=models.IntegerField(default=0),
        ),
    ]
