# Generated by Django 4.1.7 on 2023-11-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_player_accuracy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='text',
            new_name='eng_text',
        ),
        migrations.AddField(
            model_name='prompt',
            name='ita_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
