# Generated by Django 4.2.7 on 2023-11-13 15:33

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_text_prompt_eng_text_prompt_ita_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sampleimage',
            name='img',
            field=models.ImageField(max_length=1024, upload_to=main.models.content_file_name),
        ),
    ]
